"use client";

import { useState, useTransition } from "react";
import { FileText, Lightbulb, UserCheck, Share2, Printer, Sparkles, AlertTriangle } from "lucide-react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { generateWillAction } from "@/app/actions";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Separator } from "@/components/ui/separator";

const wasiyatSchema = z.object({
  prompt: z.string().min(50, "Please provide a detailed description of your wishes (at least 50 characters)."),
});

export default function WasiyatPage() {
  const { toast } = useToast();
  const [isPending, startTransition] = useTransition();
  const [willDraft, setWillDraft] = useState<string | null>(null);

  const form = useForm<z.infer<typeof wasiyatSchema>>({
    resolver: zodResolver(wasiyatSchema),
    defaultValues: {
        prompt: ""
    }
  });

  function onSubmit(data: z.infer<typeof wasiyatSchema>) {
    startTransition(async () => {
        const result = await generateWillAction(data);
        if(result.success && result.data) {
            setWillDraft(result.data.willDraft);
            toast({
                title: "Will Draft Generated",
                description: "Your Wasiyat draft has been generated by the AI assistant.",
            });
        } else {
             toast({
                title: "Error",
                description: result.error,
                variant: "destructive"
            });
        }
    });
  }

  return (
    <div className="flex flex-col gap-6">
      <header>
        <h1 className="text-3xl font-bold font-headline tracking-tight flex items-center gap-2">
          <FileText /> Wasiyat (Will) Creation
        </h1>
        <p className="text-muted-foreground">Create your Shariah-compliant will with our AI-powered assistant.</p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1 flex flex-col gap-6">
            <Card>
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <Sparkles className="text-primary"/> AI Will Assistant
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <Form {...form}>
                        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                            <FormField
                                control={form.control}
                                name="prompt"
                                render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Describe Your Wishes</FormLabel>
                                    <FormControl>
                                    <Textarea
                                        placeholder="Describe your beneficiaries, assets, and any specific instructions. For example: 'I want to leave my house at 123 Main St to my son, Ahmed. My savings of $10,000 should be split equally between my two daughters, Fatima and Aisha. I also want to donate 10% of my remaining assets to the local mosque...'"
                                        className="min-h-[200px]"
                                        {...field}
                                    />
                                    </FormControl>
                                    <FormMessage />
                                </FormItem>
                                )}
                            />
                            <Button type="submit" className="w-full" disabled={isPending}>
                                {isPending ? "Generating..." : "Generate Will Draft"}
                            </Button>
                        </form>
                    </Form>
                </CardContent>
            </Card>

            <Alert>
                <Lightbulb className="h-4 w-4" />
                <AlertTitle>Shariah Guidance</AlertTitle>
                <AlertDescription>
                   A Wasiyat can only be made for up to 1/3 of your total assets after debts and funeral expenses. The remaining 2/3 is distributed according to fixed Islamic inheritance shares (Fara'id).
                </AlertDescription>
            </Alert>
        </div>

        <div className="lg:col-span-2">
            <Card className="min-h-[600px]">
                <CardHeader>
                    <CardTitle>Generated Will Draft</CardTitle>
                    <CardDescription>This is an AI-generated draft. Please review it carefully and consult with a scholar.</CardDescription>
                </CardHeader>
                <CardContent>
                    {isPending && <div className="text-center p-8">Generating your will draft... <Sparkles className="inline-block animate-pulse" /></div>}
                    {!isPending && !willDraft && <div className="text-center p-8 text-muted-foreground">Your generated will draft will appear here.</div>}
                    {willDraft && (
                        <div className="space-y-6">
                             <Alert variant="destructive">
                                <AlertTriangle className="h-4 w-4" />
                                <AlertTitle>Disclaimer</AlertTitle>
                                <AlertDescription>
                                This is not a legally binding document. It is a draft generated for review purposes. Consult a qualified Islamic scholar and legal professional before finalizing.
                                </AlertDescription>
                            </Alert>
                            <div className="font-body whitespace-pre-wrap p-4 bg-gray-50 rounded-md border text-sm">
                                {willDraft}
                            </div>
                            <Separator />
                            <div className="flex flex-wrap gap-4 justify-between items-center">
                                <div className="space-y-2">
                                    <h4 className="font-semibold">Next Steps</h4>
                                    <div className="flex gap-2">
                                        <Button variant="outline"><UserCheck className="mr-2 h-4 w-4" /> Assign Witnesses</Button>
                                        <Button variant="outline"><Share2 className="mr-2 h-4 w-4" /> Send for Scholar Review</Button>
                                    </div>
                                </div>
                                 <Button><Printer className="mr-2 h-4 w-4" /> Print / Save as PDF</Button>
                            </div>
                        </div>
                    )}
                </CardContent>
            </Card>
        </div>
      </div>
    </div>
  );
}
